apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: txxua9v7x-nodejs
  janus-idp.io/tekton: txxua9v7x-nodejs
  backstage.io/kubernetes-id: txxua9v7x-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: txxua9v7x-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
